# Generated by Django 2.2.6 on 2019-11-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='get_expert_info_fina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('req', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='paper_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.TextField()),
                ('paper_list_top10', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='topic_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('req', models.TextField()),
            ],
        ),
    ]
